"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  AnalysisApiError,
  AnalysisJob,
  cancelJob,
  getServiceHealth,
  resultFileUrl,
  submitAb1,
  submitBatchTree,
  submitFasta,
  waitForJob,
} from "./analysisApi";
import { autoSampleId, fileStem } from "./sampleIdParser";

type InputMode = "single" | "batch" | "fasta";
type ServiceState = "checking" | "ready" | "unavailable";
type Locale = "en" | "zh";
type BatchStep =
  | { phase: "prepare"; index: number; total: number; sampleId: string }
  | { phase: "tree" }
  | null;

const acceptedFiles: Record<InputMode, string> = {
  single: ".ab1",
  batch: ".ab1",
  fasta: ".fa,.fas,.fasta,.fna",
};

const copy = {
  en: {
    brandTitle: "Orientia TSA56 Phylogenetic Typing",
    brandSubtitle: "Orientia tsutsugamushi Sanger sequence genotyping",
    navLabel: "Supporting links",
    methods: "Methods",
    citation: "Citation",
    githubPending: "Enabled after repository publication",
    workflowLabel: "Locked analysis workflow",
    workflowEyebrow: "LOCKED WORKFLOW",
    workflowInput: "AB1 QC/assembly or FASTA input",
    workflowAlignment: "Locked 60-reference alignment",
    workflowTree: "IQ-TREE phylogenetic typing",
    service: { checking: "Checking service", ready: "Service ready", unavailable: "Service unavailable" },
    inputTabs: "Input type",
    inputs: {
      single: { title: "Single AB1", hint: "Upload one or two Sanger AB1 files from the same sample." },
      batch: { title: "Batch AB1", hint: "Select multiple AB1 files; filenames are grouped into samples for one joint tree." },
      fasta: { title: "FASTA sequences", hint: "Upload one FASTA file containing 1–100 TSA56 sequences." },
    },
    sampleId: "Sample identifier",
    samplePlaceholder: "Example: OT-001",
    chooseFile: "Choose file",
    chooseFiles: "Choose files",
    noFile: "No file selected",
    selectedFiles: (files: number, samples: number) => `${files} files · ${samples} samples`,
    batchGroups: "Detected sample groups",
    additionalSamples: (count: number) => `${count} more samples`,
    start: "Start analysis",
    running: "Analysis running",
    stop: "Stop current task",
    result: "Analysis result",
    waiting: "Waiting for input",
    waitingHint: "Phylogenetic evidence, the tree and result downloads will appear here.",
    analyzing: "Analysis in progress",
    keepOpen: "Keep this page open until the current task finishes.",
    progressLabel: "Analysis progress",
    resultType: "Typing result",
    sequences: (count: number) => `${count} sequences`,
    review: "Manual review",
    group: "Group",
    decision: "Decision",
    columns: { sequence: "Sequence", genotype: "Genotype", group: "Group", support: "UFBoot", status: "Status" },
    treeAlt: "TSA56 phylogenetic tree generated by this analysis",
    treeCaption: "IQ-TREE phylogeny with the locked 60-reference panel",
    researchOnly: "Research use only · local anonymous results are retained for 24 hours by default",
    errors: {
      service: "The local analysis service is not ready. Start the Docker or native service first.",
      input: "Choose an input file first.",
      singleLimit: "A single sample accepts at most two AB1 files.",
      batchLimit: "At least one sample has more than two AB1 files. Check the filenames or split the upload.",
      generic: "The analysis did not finish. Review the local service log and try again.",
      invalid: "The input was rejected. Check the file type, sequence content and sample naming.",
      stopped: "The analysis was stopped.",
    },
    prepareStep: (index: number, total: number, id: string) => `Read QC ${index}/${total}: ${id}`,
    treeStep: "Locked-reference alignment and joint IQ-TREE inference",
  },
  zh: {
    brandTitle: "恙虫东方体 TSA56 系统发育分型",
    brandSubtitle: "Orientia tsutsugamushi Sanger 序列分型",
    navLabel: "辅助链接",
    methods: "方法",
    citation: "引用",
    githubPending: "发布仓库后启用",
    workflowLabel: "固定分析流程",
    workflowEyebrow: "固定流程",
    workflowInput: "AB1 质控/拼接或 FASTA 输入",
    workflowAlignment: "60 条参考序列固定比对",
    workflowTree: "IQ-TREE 建树分型",
    service: { checking: "正在检查服务", ready: "服务就绪", unavailable: "服务未就绪" },
    inputTabs: "输入类型",
    inputs: {
      single: { title: "单样本 AB1", hint: "上传 1–2 个同一样本的 Sanger AB1 文件。" },
      batch: { title: "批量 AB1", hint: "选择多个 AB1 文件，系统按文件名自动归组并联合建树。" },
      fasta: { title: "FASTA 序列", hint: "上传一个含 1–100 条 TSA56 序列的 FASTA 文件。" },
    },
    sampleId: "样本编号",
    samplePlaceholder: "例如：OT-001",
    chooseFile: "选择文件",
    chooseFiles: "选择多个文件",
    noFile: "尚未选择文件",
    selectedFiles: (files: number, samples: number) => `${files} 个文件 · ${samples} 个样本`,
    batchGroups: "批量样本识别结果",
    additionalSamples: (count: number) => `另有 ${count} 个样本`,
    start: "开始分析",
    running: "分析进行中",
    stop: "停止当前任务",
    result: "分析结果",
    waiting: "等待分析",
    waitingHint: "完成输入后，分型证据、系统发育树和下载文件会显示在这里。",
    analyzing: "正在分析",
    keepOpen: "当前任务完成前请保持本页面打开。",
    progressLabel: "分析进度",
    resultType: "分型结果",
    sequences: (count: number) => `${count} 条序列`,
    review: "需复核",
    group: "分组",
    decision: "判定",
    columns: { sequence: "序列", genotype: "分型", group: "分组", support: "UFBoot", status: "状态" },
    treeAlt: "本次分析生成的 TSA56 系统发育树",
    treeCaption: "固定 60 条参考序列的 IQ-TREE 系统发育树",
    researchOnly: "仅供科研使用 · 本地匿名结果默认保留 24 小时",
    errors: {
      service: "本地分析服务尚未就绪，请先启动 Docker 或原生服务。",
      input: "请先选择输入文件。",
      singleLimit: "单样本最多上传两个 AB1 文件。",
      batchLimit: "部分样本识别到超过两个 AB1 文件，请检查文件命名或分批上传。",
      generic: "分析未完成，请查看本地服务日志后重试。",
      invalid: "输入未通过检查，请核对文件类型、序列内容和样本命名。",
      stopped: "分析已停止。",
    },
    prepareStep: (index: number, total: number, id: string) => `读取与质控 ${index}/${total}：${id}`,
    treeStep: "固定参考比对与 IQ-TREE 联合建树",
  },
} as const;

function submissionId(sampleCount: number) {
  const date = new Date();
  const part = (value: number) => String(value).padStart(2, "0");
  const stamp = `${date.getFullYear()}${part(date.getMonth() + 1)}${part(date.getDate())}-${part(date.getHours())}${part(date.getMinutes())}${part(date.getSeconds())}`;
  const bytes = new Uint8Array(3);
  crypto.getRandomValues(bytes);
  const token = Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
  return `${stamp}_${sampleCount}样本_${token}`;
}

function prettyStatus(status: string | null | undefined, locale: Locale) {
  const map: Record<Locale, Record<string, string>> = {
    en: {
      auto_accepted: "Supported",
      accepted: "Supported",
      review_required: "Manual review",
      ambiguous: "Manual review",
      insufficient_support: "Insufficient support",
      pending_phylogeny: "Pending joint tree",
    },
    zh: {
      auto_accepted: "支持分型",
      accepted: "支持分型",
      review_required: "需人工复核",
      ambiguous: "需人工复核",
      insufficient_support: "支持度不足",
      pending_phylogeny: "等待联合建树",
    },
  };
  return status ? map[locale][status] || status : "—";
}

function prettyJobStatus(status: string, locale: Locale) {
  const labels: Record<Locale, Record<string, string>> = {
    en: { queued: "Queued", running: "Running", completed: "Completed", failed: "Failed", cancelled: "Cancelled" },
    zh: { queued: "排队中", running: "运行中", completed: "已完成", failed: "失败", cancelled: "已取消" },
  };
  return labels[locale][status] || status;
}

function progressMessage(job: AnalysisJob, locale: Locale, fallback: string) {
  if (locale === "zh") return job.progress?.message || fallback;
  const byStage: Record<string, string> = {
    queued: "Waiting for an analysis slot",
    prepare: "Reading chromatograms and preparing the sample sequence",
    quality: "Running trace quality control",
    assembly: "Orienting and assembling paired reads",
    mafft: "Adding samples to the locked 60-reference alignment",
    iqtree: "Running IQ-TREE phylogenetic inference",
    typing: "Assigning genotype from phylogenetic evidence",
    rendering: "Rendering the result tree and reports",
  };
  return byStage[job.progress?.stage || ""] || fallback;
}

function readableError(reason: unknown, locale: Locale) {
  const t = copy[locale];
  if (reason instanceof AnalysisApiError) {
    if (reason.status === 400 || reason.status === 413 || reason.status === 422) return t.errors.invalid;
    if (reason.status === 499) return t.errors.stopped;
    if (reason.status === 503) return t.errors.service;
    return locale === "zh" ? reason.message : t.errors.generic;
  }
  return reason instanceof Error && locale === "zh" ? reason.message : t.errors.generic;
}

function downloadLabel(label: string, locale: Locale) {
  const labels: Record<string, { en: string; zh: string }> = {
    report_json: { en: "JSON report", zh: "JSON 报告" },
    report_html: { en: "HTML report", zh: "HTML 报告" },
    consensus_fasta: { en: "Consensus FASTA", zh: "拼接序列 FASTA" },
    samples_fasta: { en: "Sample FASTA", zh: "样本序列 FASTA" },
    alignment_fasta: { en: "Reference alignment", zh: "固定参考比对" },
    tree_file: { en: "IQ-TREE treefile", zh: "IQ-TREE 原始树" },
    tree_newick: { en: "Display Newick", zh: "展示树 Newick" },
    tree_svg: { en: "Tree SVG", zh: "树图 SVG" },
    display_tree_svg: { en: "Tree SVG", zh: "树图 SVG" },
    iqtree_report: { en: "IQ-TREE report", zh: "IQ-TREE 报告" },
    iqtree_log: { en: "IQ-TREE log", zh: "IQ-TREE 日志" },
    iqtree_ufboot: { en: "UFBoot trees", zh: "UFBoot 树集" },
    iqtree_contree: { en: "Consensus tree", zh: "一致树" },
  };
  return labels[label]?.[locale] || label.replaceAll("_", " ");
}

function percentLabel(value?: number | null) {
  if (value === null || value === undefined) return "—";
  return value <= 1 ? `${Math.round(value * 100)}%` : `${Math.round(value)}%`;
}

export function GenotypingWorkspace() {
  const [locale, setLocale] = useState<Locale>("en");
  const [mode, setMode] = useState<InputMode>("single");
  const [files, setFiles] = useState<File[]>([]);
  const [sampleId, setSampleId] = useState("");
  const [service, setService] = useState<ServiceState>("checking");
  const [job, setJob] = useState<AnalysisJob | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [batchStep, setBatchStep] = useState<BatchStep>(null);
  const t = copy[locale];

  const githubUrl = (
    import.meta as ImportMeta & { env?: Record<string, string | undefined> }
  ).env?.VITE_PUBLIC_GITHUB_URL;

  useEffect(() => {
    const saved = window.localStorage.getItem("orientia-tsa56-locale");
    const detected: Locale = saved === "en" || saved === "zh"
      ? saved
      : navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";
    setLocale(detected);
    getServiceHealth()
      .then((health) => setService(health.compatible && health.ready ? "ready" : "unavailable"))
      .catch(() => setService("unavailable"));
  }, []);

  useEffect(() => {
    document.documentElement.lang = locale === "zh" ? "zh-CN" : "en";
  }, [locale]);

  const batchGroups = useMemo(() => {
    const groups = new Map<string, File[]>();
    for (const file of files) {
      const id = autoSampleId(file.name) || fileStem(file.name) || "sample";
      groups.set(id, [...(groups.get(id) || []), file]);
    }
    return Array.from(groups.entries());
  }, [files]);

  const selectedLabel = mode === "batch"
    ? t.selectedFiles(files.length, batchGroups.length)
    : files[0]?.name || t.noFile;

  const setLanguage = (next: Locale) => {
    setLocale(next);
    window.localStorage.setItem("orientia-tsa56-locale", next);
    setError("");
  };

  const switchMode = (next: InputMode) => {
    if (busy) return;
    setMode(next);
    setFiles([]);
    setSampleId("");
    setError("");
    setJob(null);
    setBatchStep(null);
  };

  const onFiles = (list: FileList | null) => {
    if (!list) return;
    const selected = Array.from(list);
    if (mode === "single") setFiles(selected.slice(0, 2));
    else if (mode === "fasta") setFiles(selected.slice(0, 1));
    else setFiles(selected);
    if (mode === "single" && !sampleId && selected[0]) {
      setSampleId(autoSampleId(selected[0].name) || fileStem(selected[0].name));
    }
    setError("");
    setJob(null);
  };

  const run = async (event: FormEvent) => {
    event.preventDefault();
    setError("");
    setJob(null);
    if (service !== "ready") {
      setError(t.errors.service);
      return;
    }
    if (!files.length) {
      setError(t.errors.input);
      return;
    }
    if (mode === "single" && files.length > 2) {
      setError(t.errors.singleLimit);
      return;
    }
    if (mode === "batch" && batchGroups.some(([, group]) => group.length > 2)) {
      setError(t.errors.batchLimit);
      return;
    }

    setBusy(true);
    try {
      if (mode === "single") {
        const submitted = await submitAb1({
          sampleId: sampleId.trim() || autoSampleId(files[0].name) || "sample",
          files,
        });
        setJob(await waitForJob(submitted, setJob));
      } else if (mode === "fasta") {
        const submitted = await submitFasta(files[0]);
        setJob(await waitForJob(submitted, setJob));
      } else {
        const batchId = submissionId(batchGroups.length);
        const preparedIds: string[] = [];
        for (let index = 0; index < batchGroups.length; index += 1) {
          const [id, groupFiles] = batchGroups[index];
          setBatchStep({ phase: "prepare", index: index + 1, total: batchGroups.length, sampleId: id });
          const submitted = await submitAb1({
            sampleId: id,
            files: groupFiles,
            mode: "prepare",
            submissionId: batchId,
            submissionSampleCount: batchGroups.length,
          });
          const prepared = await waitForJob(submitted, setJob);
          preparedIds.push(prepared.job_id);
        }
        setBatchStep({ phase: "tree" });
        const submittedTree = await submitBatchTree(preparedIds, batchId);
        setJob(await waitForJob(submittedTree, setJob));
      }
    } catch (reason) {
      setError(readableError(reason, locale));
    } finally {
      setBusy(false);
      setBatchStep(null);
    }
  };

  const stop = async () => {
    if (!job || !busy) return;
    await cancelJob(job.job_id).catch(() => undefined);
    setBusy(false);
    setError(t.errors.stopped);
  };

  const batchStepText = batchStep?.phase === "prepare"
    ? t.prepareStep(batchStep.index, batchStep.total, batchStep.sampleId)
    : batchStep?.phase === "tree" ? t.treeStep : "";

  const treeFilename = job?.files.tree_svg || job?.files.display_tree_svg;
  const resultRows = job?.summary?.tree_typing_results || [];
  const rowSupports = resultRows
    .map((row) => row.support)
    .filter((value): value is number => typeof value === "number");
  const support = job?.summary?.tree_typing_support
    ?? (rowSupports.length ? Math.min(...rowSupports) : null);
  const rawStatus = job?.summary?.tree_typing_status || job?.summary?.target_status;
  const status = rawStatus === "completed" && resultRows.length
    ? (resultRows.every((row) => row.auto_accepted) ? "auto_accepted" : "review_required")
    : rawStatus;

  return (
    <main>
      <header className="site-header">
        <div className="brand">
          <img src="/favicon.svg" alt="" width="44" height="44" />
          <div>
            <h1>{t.brandTitle}</h1>
            <p>{t.brandSubtitle}</p>
          </div>
          <span className="version-badge">V1.0 · ARTICLE WORKFLOW</span>
        </div>
        <nav aria-label={t.navLabel}>
          <div className="language-toggle" role="group" aria-label="Language / 语言">
            <button type="button" className={locale === "en" ? "active" : ""} aria-pressed={locale === "en"} onClick={() => setLanguage("en")}>EN</button>
            <button type="button" className={locale === "zh" ? "active" : ""} aria-pressed={locale === "zh"} onClick={() => setLanguage("zh")}>中文</button>
          </div>
          <a href="#workflow">{t.methods}</a>
          <a href="#citation">{t.citation}</a>
          {githubUrl ? <a href={githubUrl} target="_blank" rel="noreferrer">GitHub</a> : <span title={t.githubPending}>GitHub</span>}
        </nav>
      </header>

      <section className="workflow-strip" id="workflow" aria-label={t.workflowLabel}>
        <span className="eyebrow">{t.workflowEyebrow}</span>
        <strong>{t.workflowInput}</strong>
        <i aria-hidden="true">→</i>
        <strong>{t.workflowAlignment}</strong>
        <i aria-hidden="true">→</i>
        <strong>{t.workflowTree}</strong>
        <span className={`service-chip ${service}`}>
          {t.service[service]}
        </span>
      </section>

      <div className="workspace-grid">
        <section className="input-panel" aria-labelledby="input-title">
          <div className="mode-tabs" role="tablist" aria-label={t.inputTabs}>
            {(["single", "batch", "fasta"] as InputMode[]).map((item) => (
              <button
                key={item}
                type="button"
                role="tab"
                aria-selected={mode === item}
                className={mode === item ? "active" : ""}
                onClick={() => switchMode(item)}
              >
                {t.inputs[item].title}
              </button>
            ))}
          </div>

          <form onSubmit={run}>
            <div className="panel-heading">
              <span className="eyebrow">INPUT</span>
              <h2 id="input-title">{t.inputs[mode].title}</h2>
              <p>{t.inputs[mode].hint}</p>
            </div>

            {mode === "single" && (
              <label className="field-label">
                {t.sampleId}
                <input
                  value={sampleId}
                  onChange={(event) => setSampleId(event.target.value)}
                  placeholder={t.samplePlaceholder}
                  maxLength={60}
                  disabled={busy}
                />
              </label>
            )}

            <label className="upload-zone">
              <input
                type="file"
                accept={acceptedFiles[mode]}
                multiple={mode !== "fasta"}
                onChange={(event) => onFiles(event.target.files)}
                disabled={busy}
              />
              <span className="upload-mark" aria-hidden="true">＋</span>
              <strong>{mode === "batch" ? t.chooseFiles : t.chooseFile}</strong>
              <small>{selectedLabel}</small>
            </label>

            {mode === "batch" && batchGroups.length > 0 && (
              <div className="batch-preview" aria-label={t.batchGroups}>
                {batchGroups.slice(0, 6).map(([id, group]) => (
                  <span key={id}>{id}<b>{group.length}</b></span>
                ))}
                {batchGroups.length > 6 && <span>{t.additionalSamples(batchGroups.length - 6)}</span>}
              </div>
            )}

            <button className="primary-button" type="submit" disabled={busy || files.length === 0 || service !== "ready"}>
              {busy ? t.running : t.start}
            </button>
            {busy && (
              <button className="stop-button" type="button" onClick={stop}>{t.stop}</button>
            )}
          </form>
        </section>

        <section className="result-panel" aria-labelledby="result-title">
          <div className="result-header">
            <div>
              <span className="eyebrow">RESULT</span>
              <h2 id="result-title">{t.result}</h2>
            </div>
            {job && <span className={`job-status ${job.status}`}>{prettyJobStatus(job.status, locale)}</span>}
          </div>

          <div aria-live="polite" aria-atomic="true">
            {error && <div className="error-box" role="alert">{error}</div>}
            {!job && !error && (
              <div className="empty-state">
                <img src="/favicon.svg" alt="" width="54" height="54" />
                <h3>{t.waiting}</h3>
                <p>{t.waitingHint}</p>
              </div>
            )}
            {job && (job.status === "queued" || job.status === "running") && (
              <div className="progress-state">
                <div className="progress-copy">
                  <span>{batchStepText || progressMessage(job, locale, t.analyzing)}</span>
                  <strong>{Math.round(job.progress?.percent || 0)}%</strong>
                </div>
                <div className="progress-track" aria-label={t.progressLabel}>
                  <span style={{ width: `${Math.max(2, job.progress?.percent || 0)}%` }} />
                </div>
                <p>{t.keepOpen}</p>
              </div>
            )}
            {job?.status === "completed" && job.summary && (
              <div className="completed-state">
                <div className="result-summary">
                  <div><span>{t.resultType}</span><strong>{resultRows.length ? t.sequences(resultRows.length) : (job.summary.predicted_type || t.review)}</strong></div>
                  <div><span>{t.group}</span><strong>{job.summary.predicted_group || "—"}</strong></div>
                  <div><span>UFBoot</span><strong>{percentLabel(support)}</strong></div>
                  <div><span>{t.decision}</span><strong>{prettyStatus(status, locale)}</strong></div>
                </div>

                {resultRows.length > 0 && (
                  <div className="table-wrap">
                    <table>
                      <thead><tr><th>{t.columns.sequence}</th><th>{t.columns.genotype}</th><th>{t.columns.group}</th><th>{t.columns.support}</th><th>{t.columns.status}</th></tr></thead>
                      <tbody>
                        {resultRows.map((row) => (
                          <tr key={row.sample_id}>
                            <td>{row.sample_id}</td>
                            <td>{row.predicted_new_genotype || "—"}</td>
                            <td>{row.predicted_new_group || "—"}</td>
                            <td>{percentLabel(row.support)}</td>
                            <td>{prettyStatus(row.status, locale)}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}

                {treeFilename && (
                  <figure className="tree-card">
                    <img src={resultFileUrl(job.job_id, treeFilename)} alt={t.treeAlt} />
                    <figcaption>{t.treeCaption}</figcaption>
                  </figure>
                )}

                <div className="download-row">
                  {Object.entries(job.files).map(([label, filename]) => (
                    <a key={label} href={resultFileUrl(job.job_id, filename)} download>{downloadLabel(label, locale)}</a>
                  ))}
                </div>
              </div>
            )}
          </div>
        </section>
      </div>

      <footer id="citation">
        <span>{t.researchOnly}</span>
        <span>V1.0 · 60ref · MAFFT 7.525 · IQ-TREE 3.0.1</span>
      </footer>
    </main>
  );
}
