"use client";

import {
  DragEvent,
  FormEvent,
  PointerEvent as ReactPointerEvent,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from "react";
import {
  AnalysisApiError,
  AnalysisJob,
  cancelJob,
  getJob,
  getServiceHealth,
  resultFileUrl,
  submitAb1,
  submitBatchTree,
  submitFasta,
  waitForJob,
} from "./analysisApi";
import { autoSampleId, fileStem, groupBatchFiles } from "./sampleIdParser";
import { collectDroppedFiles } from "./droppedFiles";
import { BatchPreparationFailure, prepareBatchSamples } from "./batchPreparation";
import {
  parseSessionHistory,
  SESSION_HISTORY_KEY,
  SessionHistoryEntry,
  updateSessionHistoryStatus,
  upsertSessionHistory,
} from "./sessionHistory";
import { buildTypingResultsCsv } from "./typingResultsCsv";

type InputMode = "single" | "batch" | "fasta";
type ServiceState = "checking" | "ready" | "unavailable";
type Locale = "en" | "zh";
type BatchStep =
  | { phase: "prepare"; index: number; total: number; sampleId: string }
  | { phase: "tree" }
  | null;

type TreeDragState = {
  pointerId: number;
  viewport: HTMLDivElement;
  startClientX: number;
  startClientY: number;
  startScrollLeft: number;
  startScrollTop: number;
};

const acceptedFiles: Record<InputMode, string> = {
  single: ".ab1",
  batch: ".ab1",
  fasta: ".fa,.fas,.fasta,.fna",
};

const copy = {
  en: {
    brandTitle: "Orientia TSA56 Phylogenetic Typing",
    brandSubtitle: "Orientia tsutsugamushi Sanger sequence genotyping",
    navLabel: "Supporting links",
    methods: "Methods",
    citation: "Citation",
    workflowLabel: "Analysis workflow",
    workflowEyebrow: "WORKFLOW",
    workflowInput: "AB1 QC/assembly or FASTA input",
    workflowAlignment: "60-reference alignment",
    workflowTree: "IQ-TREE phylogenetic typing",
    sessionHistory: "Session history",
    clearCurrentResult: "Clear current result",
    service: { checking: "Checking service", ready: "Service ready", unavailable: "Service unavailable" },
    inputTabs: "Input type",
    inputs: {
      single: { title: "Single AB1", hint: "Upload one or two Sanger AB1 files from the same sample." },
      batch: { title: "Batch AB1", hint: "Select multiple AB1 files; filenames are grouped into samples for one joint tree." },
      fasta: { title: "FASTA sequences", hint: "Upload one FASTA file containing 1–100 TSA56 sequences." },
    },
    sampleId: "Sample identifier",
    samplePlaceholder: "Example: OT-001",
    chooseFile: "Choose file",
    chooseFiles: "Choose files",
    chooseFolder: "Choose folder",
    dropPrompt: "Drop files or a folder here",
    dropActive: "Release to add files",
    noFile: "No file selected",
    selectedReads: (files: number) => `${files} files selected`,
    selectedFiles: (files: number, samples: number) => `${files} files · ${samples} samples`,
    batchGroups: "Detected sample groups",
    additionalSamples: (count: number) => `${count} more samples`,
    viewAllSamples: (count: number) => `View all ${count} samples`,
    sampleListTitle: "Detected sample list",
    sampleListHint: (files: number, samples: number) => `${files} AB1 files are grouped into ${samples} samples.`,
    sampleFiles: (count: number) => `${count} AB1 file${count === 1 ? "" : "s"}`,
    exportResults: "Export CSV",
    start: "Start analysis",
    running: "Analysis running",
    stop: "Stop current task",
    result: "Analysis result",
    waiting: "Waiting for input",
    waitingHint: "Phylogenetic evidence, the tree and result downloads will appear here.",
    analyzing: "Analysis in progress",
    keepOpen: "Keep this page open until the current task finishes.",
    progressLabel: "Analysis progress",
    resultType: "Typing result",
    newGenotype: "New genotype",
    oldGenotype: "Legacy genotype",
    newGroup: "New group",
    oldGroup: "Legacy group",
    sequences: (count: number) => `${count} sequences`,
    review: "Manual review",
    group: "Group",
    decision: "Decision",
    columns: { sequence: "Sequence", newGenotype: "New genotype", oldGenotype: "Legacy genotype", newGroup: "New group", oldGroup: "Legacy group", support: "Genotype-anchor UFBoot", status: "Decision" },
    supportNote: "Genotype-anchor UFBoot is the boundary support of the complete reference-genotype clade, not the local sample–nearest-reference branch shown on the tree. Automatic acceptance requires ≥95%.",
    treeAlt: "TSA56 phylogenetic tree generated by this analysis",
    treeCaption: "IQ-TREE phylogeny with the 60-reference panel",
    researchOnly: "Research use only · local anonymous results are retained for 24 hours by default",
    excludedSamples: "Samples excluded after QC",
    excludedSummary: (failed: number) => `${failed} sample${failed === 1 ? "" : "s"} failed QC; all other valid samples continue to the joint tree.`,
    excludedReason: "Reason",
    historyTitle: "Current session submissions",
    historyHint: "Only analyses submitted in this browser session are listed. Server result files are retained for 24 hours by default.",
    historyEmpty: "No analysis has been submitted in this session.",
    historyOpenResult: "View result",
    historyLoading: "Loading",
    historyUnavailable: "This result is unavailable or has expired.",
    close: "Close",
    treeInteractionHint: "Mouse wheel to zoom · drag to pan",
    treeZoomLevel: "Zoom",
    treeResetZoom: "Reset zoom",
    treeExpand: "Expand tree",
    treeViewerTitle: "Phylogenetic tree viewer",
    errors: {
      service: "The local analysis service is not ready. Start the Docker or native service first.",
      input: "Choose an input file first.",
      singleLimit: "A single sample accepts at most two AB1 files.",
      batchLimit: "At least one sample has more than two AB1 files. Check the filenames or split the upload.",
      generic: "The analysis did not finish. Review the local service log and try again.",
      invalid: "The input was rejected. Check the file type, sequence content and sample naming.",
      unsupportedFiles: "No supported files were found. Use AB1 files or a FASTA file for the selected input mode.",
      folderRead: "The folder could not be read. Choose the files directly and try again.",
      stopped: "The analysis was stopped.",
      allBatchFailed: "No sample passed AB1 quality control, so the joint tree was not started.",
    },
    prepareStep: (index: number, total: number, id: string) => `Read QC ${index}/${total}: ${id}`,
    treeStep: "60-reference alignment and joint IQ-TREE inference",
  },
  zh: {
    brandTitle: "恙虫东方体 TSA56 系统发育分型",
    brandSubtitle: "Orientia tsutsugamushi Sanger 序列分型",
    navLabel: "辅助链接",
    methods: "方法",
    citation: "引用",
    workflowLabel: "固定分析流程",
    workflowEyebrow: "分析流程",
    workflowInput: "AB1 质控/拼接或 FASTA 输入",
    workflowAlignment: "60 条参考序列比对",
    workflowTree: "IQ-TREE 建树分型",
    sessionHistory: "本次登录历史",
    clearCurrentResult: "清空当前结果",
    service: { checking: "正在检查服务", ready: "服务就绪", unavailable: "服务未就绪" },
    inputTabs: "输入类型",
    inputs: {
      single: { title: "单样本 AB1", hint: "上传 1–2 个同一样本的 Sanger AB1 文件。" },
      batch: { title: "批量 AB1", hint: "选择多个 AB1 文件，系统按文件名自动归组并联合建树。" },
      fasta: { title: "FASTA 序列", hint: "上传一个含 1–100 条 TSA56 序列的 FASTA 文件。" },
    },
    sampleId: "样本编号",
    samplePlaceholder: "例如：OT-001",
    chooseFile: "选择文件",
    chooseFiles: "选择多个文件",
    chooseFolder: "选择文件夹",
    dropPrompt: "拖拽文件或文件夹到这里",
    dropActive: "松开即可添加文件",
    noFile: "尚未选择文件",
    selectedReads: (files: number) => `已选择 ${files} 个文件`,
    selectedFiles: (files: number, samples: number) => `${files} 个文件 · ${samples} 个样本`,
    batchGroups: "批量样本识别结果",
    additionalSamples: (count: number) => `另有 ${count} 个样本`,
    viewAllSamples: (count: number) => `查看全部 ${count} 个样本`,
    sampleListTitle: "完整样本列表",
    sampleListHint: (files: number, samples: number) => `${files} 个 AB1 文件已归组为 ${samples} 个样本。`,
    sampleFiles: (count: number) => `${count} 个 AB1 文件`,
    exportResults: "导出 CSV",
    start: "开始分析",
    running: "分析进行中",
    stop: "停止当前任务",
    result: "分析结果",
    waiting: "等待分析",
    waitingHint: "完成输入后，分型证据、系统发育树和下载文件会显示在这里。",
    analyzing: "正在分析",
    keepOpen: "当前任务完成前请保持本页面打开。",
    progressLabel: "分析进度",
    resultType: "分型结果",
    newGenotype: "新基因型",
    oldGenotype: "旧基因型",
    newGroup: "新分组",
    oldGroup: "旧分组",
    sequences: (count: number) => `${count} 条序列`,
    review: "需复核",
    group: "分组",
    decision: "判定",
    columns: { sequence: "序列", newGenotype: "新基因型", oldGenotype: "旧基因型", newGroup: "新分组", oldGroup: "旧分组", support: "基因型锚定支 UFBoot", status: "判定" },
    supportNote: "基因型锚定支 UFBoot 是完整参考基因型支系的边界支持度，不是树图中样本与单条最近参考组成的局部分支支持度；自动接受阈值为 ≥95%。",
    treeAlt: "本次分析生成的 TSA56 系统发育树",
    treeCaption: "固定 60 条参考序列的 IQ-TREE 系统发育树",
    researchOnly: "仅供科研使用 · 本地匿名结果默认保留 24 小时",
    excludedSamples: "质控失败并排除的样本",
    excludedSummary: (failed: number) => `${failed} 个样本质控失败；其余合格样本继续联合建树。`,
    excludedReason: "失败原因",
    historyTitle: "本次登录历史提交结果",
    historyHint: "仅显示当前浏览器会话提交的分析；服务器结果文件默认保留 24 小时。",
    historyEmpty: "本次会话尚未提交分析。",
    historyOpenResult: "查看结果",
    historyLoading: "正在读取",
    historyUnavailable: "该结果不可用或已过期。",
    close: "关闭",
    treeInteractionHint: "鼠标滚轮缩放 · 按住左键拖拽移动",
    treeZoomLevel: "缩放",
    treeResetZoom: "恢复 100%",
    treeExpand: "展开查看",
    treeViewerTitle: "系统发育树查看器",
    errors: {
      service: "本地分析服务尚未就绪，请先启动 Docker 或原生服务。",
      input: "请先选择输入文件。",
      singleLimit: "单样本最多上传两个 AB1 文件。",
      batchLimit: "部分样本识别到超过两个 AB1 文件，请检查文件命名或分批上传。",
      generic: "分析未完成，请查看本地服务日志后重试。",
      invalid: "输入未通过检查，请核对文件类型、序列内容和样本命名。",
      unsupportedFiles: "未找到当前模式支持的文件。请选择 AB1 文件或 FASTA 文件。",
      folderRead: "无法读取该文件夹，请直接选择文件后重试。",
      stopped: "分析已停止。",
      allBatchFailed: "没有样本通过 AB1 质控，未启动联合建树。",
    },
    prepareStep: (index: number, total: number, id: string) => `读取与质控 ${index}/${total}：${id}`,
    treeStep: "固定参考比对与 IQ-TREE 联合建树",
  },
} as const;

function submissionId(sampleCount: number) {
  const date = new Date();
  const part = (value: number) => String(value).padStart(2, "0");
  const stamp = `${date.getFullYear()}${part(date.getMonth() + 1)}${part(date.getDate())}-${part(date.getHours())}${part(date.getMinutes())}${part(date.getSeconds())}`;
  const bytes = new Uint8Array(3);
  crypto.getRandomValues(bytes);
  const token = Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
  return `${stamp}_${sampleCount}样本_${token}`;
}

function prettyStatus(status: string | null | undefined, locale: Locale) {
  const map: Record<Locale, Record<string, string>> = {
    en: {
      auto_accepted: "Supported",
      accepted: "Supported",
      matched: "Supported",
      review_required: "Manual review",
      review_low_support: "Low support — manual review",
      review_missing_support: "Missing support — manual review",
      review_distance_margin: "Distance margin — manual review",
      review_topology_distance_conflict: "Topology conflict — manual review",
      ambiguous: "Manual review",
      insufficient_support: "Insufficient support",
      pending_phylogeny: "Pending joint tree",
    },
    zh: {
      auto_accepted: "支持分型",
      accepted: "支持分型",
      matched: "支持分型",
      review_required: "需人工复核",
      review_low_support: "支持度不足，需人工复核",
      review_missing_support: "缺少支持度，需人工复核",
      review_distance_margin: "距离边界不足，需人工复核",
      review_topology_distance_conflict: "拓扑与距离冲突，需人工复核",
      ambiguous: "需人工复核",
      insufficient_support: "支持度不足",
      pending_phylogeny: "等待联合建树",
    },
  };
  return status ? map[locale][status] || status : "—";
}

function prettyJobStatus(status: string, locale: Locale) {
  const labels: Record<Locale, Record<string, string>> = {
    en: { queued: "Queued", running: "Running", completed: "Completed", failed: "Failed", cancelled: "Cancelled" },
    zh: { queued: "排队中", running: "运行中", completed: "已完成", failed: "失败", cancelled: "已取消" },
  };
  return labels[locale][status] || status;
}

function progressMessage(job: AnalysisJob, locale: Locale, fallback: string) {
  if (locale === "zh") return job.progress?.message || fallback;
  const byStage: Record<string, string> = {
    queued: "Waiting for an analysis slot",
    prepare: "Reading chromatograms and preparing the sample sequence",
    quality: "Running trace quality control",
    assembly: "Orienting and assembling paired reads",
    mafft: "Adding samples to the 60-reference alignment",
    iqtree: "Running IQ-TREE phylogenetic inference",
    typing: "Assigning genotype from phylogenetic evidence",
    rendering: "Rendering the result tree and reports",
  };
  return byStage[job.progress?.stage || ""] || fallback;
}

function readableError(reason: unknown, locale: Locale) {
  const t = copy[locale];
  if (reason instanceof AnalysisApiError) {
    if (reason.status === 400 || reason.status === 413 || reason.status === 422) {
      return locale === "zh"
        ? `${t.errors.invalid}（服务端原因：${reason.message}）`
        : reason.message;
    }
    if (reason.status === 499) return t.errors.stopped;
    if (reason.status === 503) return t.errors.service;
    return locale === "zh" ? reason.message : t.errors.generic;
  }
  return reason instanceof Error && locale === "zh" ? reason.message : t.errors.generic;
}

function batchFailureReason(reason: unknown, locale: Locale) {
  if (locale === "en" && reason instanceof AnalysisApiError && /质控失败|测序质量差|双峰/.test(reason.message)) {
    return "AB1 quality control failed; the sample was excluded from the joint tree.";
  }
  return readableError(reason, locale).replace(/^质控失败：\s*质控失败：\s*/, "质控失败：");
}

function shouldAbortBatch(reason: unknown) {
  if (!(reason instanceof AnalysisApiError)) return true;
  return ![400, 413, 422, 500].includes(reason.status);
}

function downloadLabel(label: string, locale: Locale) {
  const labels: Record<string, { en: string; zh: string }> = {
    report_json: { en: "JSON report", zh: "JSON 报告" },
    report_html: { en: "HTML report", zh: "HTML 报告" },
    consensus_fasta: { en: "Consensus FASTA", zh: "拼接序列 FASTA" },
    samples_fasta: { en: "Sample FASTA", zh: "样本序列 FASTA" },
    alignment_fasta: { en: "Reference alignment", zh: "固定参考比对" },
    tree_file: { en: "IQ-TREE treefile", zh: "IQ-TREE 原始树" },
    tree_newick: { en: "Display Newick", zh: "展示树 Newick" },
    tree_svg: { en: "Tree SVG", zh: "树图 SVG" },
    display_tree_svg: { en: "Tree SVG", zh: "树图 SVG" },
    iqtree_report: { en: "IQ-TREE report", zh: "IQ-TREE 报告" },
    iqtree_log: { en: "IQ-TREE log", zh: "IQ-TREE 日志" },
    iqtree_ufboot: { en: "UFBoot trees", zh: "UFBoot 树集" },
    iqtree_contree: { en: "Consensus tree", zh: "一致树" },
  };
  return labels[label]?.[locale] || label.replaceAll("_", " ");
}

function percentLabel(value?: number | null) {
  if (value === null || value === undefined) return "—";
  return value <= 1 ? `${Math.round(value * 100)}%` : `${Math.round(value)}%`;
}

function submittedAtLabel(value: number, locale: Locale) {
  return new Intl.DateTimeFormat(locale === "zh" ? "zh-CN" : "en", {
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
  }).format(new Date(value));
}

function clampTreeZoom(value: number) {
  return Math.min(300, Math.max(50, value));
}

export function GenotypingWorkspace() {
  const [locale, setLocale] = useState<Locale>("en");
  const [mode, setMode] = useState<InputMode>("single");
  const [files, setFiles] = useState<File[]>([]);
  const [sampleId, setSampleId] = useState("");
  const [service, setService] = useState<ServiceState>("checking");
  const [job, setJob] = useState<AnalysisJob | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [batchStep, setBatchStep] = useState<BatchStep>(null);
  const [batchFailures, setBatchFailures] = useState<BatchPreparationFailure[]>([]);
  const [dragActive, setDragActive] = useState(false);
  const [sessionHistory, setSessionHistory] = useState<SessionHistoryEntry[]>([]);
  const [historyOpen, setHistoryOpen] = useState(false);
  const [historyLoadingId, setHistoryLoadingId] = useState<string | null>(null);
  const [historyError, setHistoryError] = useState("");
  const [sampleListOpen, setSampleListOpen] = useState(false);
  const [treeExpanded, setTreeExpanded] = useState(false);
  const [treeZoom, setTreeZoom] = useState(100);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const folderInputRef = useRef<HTMLInputElement>(null);
  const treeViewportRef = useRef<HTMLDivElement>(null);
  const expandedTreeViewportRef = useRef<HTMLDivElement>(null);
  const treeDragRef = useRef<TreeDragState | null>(null);
  const dragDepthRef = useRef(0);
  const t = copy[locale];

  const finishTreeDrag = useCallback((pointerId?: number) => {
    const drag = treeDragRef.current;
    if (!drag || (pointerId !== undefined && drag.pointerId !== pointerId)) return;
    treeDragRef.current = null;
    drag.viewport.classList.remove("is-dragging");
    if (drag.viewport.hasPointerCapture(drag.pointerId)) {
      drag.viewport.releasePointerCapture(drag.pointerId);
    }
  }, []);

  const githubUrl = (
    import.meta as ImportMeta & { env?: Record<string, string | undefined> }
  ).env?.VITE_PUBLIC_GITHUB_URL
    || "https://github.com/xiaoyaobujue/orientia-tsa56-phylogenetic-typing";
  const repositoryUrl = githubUrl.replace(/\/+$/, "");
  const documentationPath = locale === "zh" ? "docs/zh-CN" : "docs";
  const methodsUrl = `${repositoryUrl}/blob/main/${documentationPath}/METHODS.md`;
  const citationUrl = `${repositoryUrl}/blob/main/${documentationPath}/CITATION.md`;

  useEffect(() => {
    const localeTimer = window.setTimeout(() => {
      const saved = window.localStorage.getItem("orientia-tsa56-locale");
      const detected: Locale = saved === "en" || saved === "zh"
        ? saved
        : navigator.language.toLowerCase().startsWith("zh") ? "zh" : "en";
      setLocale(detected);
    }, 0);
    getServiceHealth()
      .then((health) => setService(health.compatible && health.ready ? "ready" : "unavailable"))
      .catch(() => setService("unavailable"));
    return () => window.clearTimeout(localeTimer);
  }, []);

  useEffect(() => {
    const historyTimer = window.setTimeout(() => {
      setSessionHistory(parseSessionHistory(window.sessionStorage.getItem(SESSION_HISTORY_KEY)));
    }, 0);
    return () => window.clearTimeout(historyTimer);
  }, []);

  useEffect(() => {
    if (!historyOpen && !sampleListOpen && !treeExpanded) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== "Escape") return;
      finishTreeDrag();
      setHistoryOpen(false);
      setSampleListOpen(false);
      setTreeExpanded(false);
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, [finishTreeDrag, historyOpen, sampleListOpen, treeExpanded]);

  useEffect(() => {
    document.documentElement.lang = locale === "zh" ? "zh-CN" : "en";
  }, [locale]);

  useEffect(() => {
    const folderInput = folderInputRef.current;
    if (!folderInput) return;
    folderInput.setAttribute("webkitdirectory", "");
    folderInput.setAttribute("directory", "");
  }, []);

  const batchGroups = useMemo(() => {
    return groupBatchFiles(files);
  }, [files]);

  const selectedLabel = mode === "batch"
    ? t.selectedFiles(files.length, batchGroups.length)
    : files.length > 1 ? t.selectedReads(files.length) : files[0]?.name || t.noFile;

  const updateVisibleJob = (nextJob: AnalysisJob) => {
    setJob(nextJob);
    setSessionHistory((current) => {
      if (!current.some((entry) => entry.jobId === nextJob.job_id)) return current;
      const updated = updateSessionHistoryStatus(current, nextJob.job_id, nextJob.status);
      window.sessionStorage.setItem(SESSION_HISTORY_KEY, JSON.stringify(updated));
      return updated;
    });
  };

  const rememberSubmittedJob = (
    submitted: AnalysisJob,
    label: string,
    submissionMode: InputMode,
  ) => {
    const entry: SessionHistoryEntry = {
      jobId: submitted.job_id,
      label,
      mode: submissionMode,
      submittedAt: Date.now(),
      status: submitted.status,
    };
    setSessionHistory((current) => {
      const updated = upsertSessionHistory(current, entry);
      window.sessionStorage.setItem(SESSION_HISTORY_KEY, JSON.stringify(updated));
      return updated;
    });
    setJob(submitted);
    setTreeZoom(100);
    setTreeExpanded(false);
    return submitted;
  };

  const clearCurrentResult = () => {
    if (busy) return;
    setJob(null);
    setError("");
    setBatchStep(null);
    setBatchFailures([]);
    setTreeExpanded(false);
    setTreeZoom(100);
  };

  const restoreHistoryResult = async (entry: SessionHistoryEntry) => {
    if (busy) return;
    setHistoryError("");
    setHistoryLoadingId(entry.jobId);
    try {
      const restored = await getJob(entry.jobId);
      updateVisibleJob(restored);
      setTreeZoom(100);
      setTreeExpanded(false);
      setError("");
      setBatchStep(null);
      setBatchFailures([]);
      setHistoryOpen(false);
      if (restored.status === "failed") {
        setError(restored.error || t.historyUnavailable);
      } else if (restored.status === "cancelled") {
        setError(t.errors.stopped);
      } else if (restored.status === "queued" || restored.status === "running") {
        setBusy(true);
        try {
          updateVisibleJob(await waitForJob(restored, updateVisibleJob));
        } catch (reason) {
          setError(readableError(reason, locale));
        } finally {
          setBusy(false);
        }
      }
    } catch {
      setHistoryError(t.historyUnavailable);
    } finally {
      setHistoryLoadingId(null);
    }
  };

  const setLanguage = (next: Locale) => {
    setLocale(next);
    window.localStorage.setItem("orientia-tsa56-locale", next);
    setError("");
  };

  const switchMode = (next: InputMode) => {
    if (busy) return;
    setMode(next);
    setFiles([]);
    setSampleId("");
    setError("");
    setBatchStep(null);
    setBatchFailures([]);
    setDragActive(false);
    dragDepthRef.current = 0;
  };

  const onFiles = (list: FileList | File[] | null) => {
    if (!list) return;
    const validExtensions = acceptedFiles[mode].split(",");
    const selected = Array.from(list).filter((file) =>
      validExtensions.some((extension) => file.name.toLowerCase().endsWith(extension))
    );
    if (selected.length === 0) {
      setFiles([]);
      setError(t.errors.unsupportedFiles);
      setBatchFailures([]);
      return;
    }
    if (mode === "single") setFiles(selected.slice(0, 2));
    else if (mode === "fasta") setFiles(selected.slice(0, 1));
    else setFiles(selected);
    if (mode === "single" && !sampleId && selected[0]) {
      setSampleId(autoSampleId(selected[0].name) || fileStem(selected[0].name));
    }
    setError("");
    setBatchFailures([]);
  };

  const onDragEnter = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    if (busy) return;
    dragDepthRef.current += 1;
    setDragActive(true);
  };

  const onDragOver = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = busy ? "none" : "copy";
  };

  const onDragLeave = (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    if (busy) return;
    dragDepthRef.current = Math.max(0, dragDepthRef.current - 1);
    if (dragDepthRef.current === 0) setDragActive(false);
  };

  const onDrop = async (event: DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    dragDepthRef.current = 0;
    setDragActive(false);
    if (busy) return;
    try {
      onFiles(await collectDroppedFiles(event.dataTransfer));
    } catch {
      setError(t.errors.folderRead);
    }
  };

  const run = async (event: FormEvent) => {
    event.preventDefault();
    setError("");
    setJob(null);
    setBatchFailures([]);
    if (service !== "ready") {
      setError(t.errors.service);
      return;
    }
    if (!files.length) {
      setError(t.errors.input);
      return;
    }
    if (mode === "single" && files.length > 2) {
      setError(t.errors.singleLimit);
      return;
    }
    if (mode === "batch" && batchGroups.some(([, group]) => group.length > 2)) {
      setError(t.errors.batchLimit);
      return;
    }

    setBusy(true);
    try {
      if (mode === "single") {
        const submitted = await submitAb1({
          sampleId: sampleId.trim() || autoSampleId(files[0].name) || "sample",
          files,
        });
        const tracked = rememberSubmittedJob(
          submitted,
          sampleId.trim() || autoSampleId(files[0].name) || fileStem(files[0].name),
          "single",
        );
        updateVisibleJob(await waitForJob(tracked, updateVisibleJob));
      } else if (mode === "fasta") {
        const submitted = await submitFasta(files[0]);
        const tracked = rememberSubmittedJob(submitted, files[0].name, "fasta");
        updateVisibleJob(await waitForJob(tracked, updateVisibleJob));
      } else {
        const batchId = submissionId(batchGroups.length);
        const prepared = await prepareBatchSamples({
          samples: batchGroups.map(([id, groupFiles]) => ({ sampleId: id, payload: groupFiles })),
          onProgress: (index, total, id) => {
            setBatchStep({ phase: "prepare", index, total, sampleId: id });
          },
          prepare: async ({ sampleId: id, payload: groupFiles }) => {
            const submitted = await submitAb1({
              sampleId: id,
              files: groupFiles,
              mode: "prepare",
              submissionId: batchId,
              submissionSampleCount: batchGroups.length,
            });
            return (await waitForJob(submitted, updateVisibleJob)).job_id;
          },
          describeFailure: (reason) => batchFailureReason(reason, locale),
          shouldAbort: shouldAbortBatch,
          onFailuresChanged: setBatchFailures,
        });
        if (prepared.preparedJobIds.length === 0) {
          setJob(null);
          setError(t.errors.allBatchFailed);
          return;
        }
        setBatchStep({ phase: "tree" });
        const submittedTree = await submitBatchTree(prepared.preparedJobIds, batchId);
        const batchLabel = batchGroups.length <= 3
          ? batchGroups.map(([id]) => id).join(", ")
          : `${batchGroups.slice(0, 3).map(([id]) => id).join(", ")} +${batchGroups.length - 3}`;
        const tracked = rememberSubmittedJob(submittedTree, batchLabel, "batch");
        updateVisibleJob(await waitForJob(tracked, updateVisibleJob));
      }
    } catch (reason) {
      setError(readableError(reason, locale));
    } finally {
      setBusy(false);
      setBatchStep(null);
    }
  };

  const stop = async () => {
    if (!job || !busy) return;
    const cancelled = await cancelJob(job.job_id).catch(() => undefined);
    if (cancelled) updateVisibleJob(cancelled);
    setBusy(false);
    setError(t.errors.stopped);
  };

  const batchStepText = batchStep?.phase === "prepare"
    ? t.prepareStep(batchStep.index, batchStep.total, batchStep.sampleId)
    : batchStep?.phase === "tree" ? t.treeStep : "";

  const treeFilename = job?.files.tree_svg || job?.files.display_tree_svg;
  const resultRows = job?.summary?.tree_typing_results || [];

  const exportTypingResults = () => {
    if (!job || resultRows.length === 0) return;
    const csv = buildTypingResultsCsv(
      resultRows,
      t.columns,
      (rowStatus) => prettyStatus(rowStatus, locale),
    );
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a");
    link.href = url;
    link.download = `tsa56_typing_results_${job.job_id.slice(0, 8)}.csv`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 0);
  };
  const treeImageUrl = job && treeFilename ? resultFileUrl(job.job_id, treeFilename) : "";
  const onTreeWheel = useCallback((event: WheelEvent) => {
    event.preventDefault();
    event.stopPropagation();
    if (event.deltaY === 0) return;
    const viewport = event.currentTarget as HTMLDivElement;
    const bounds = viewport.getBoundingClientRect();
    const localX = event.clientX - bounds.left;
    const localY = event.clientY - bounds.top;
    const contentX = viewport.scrollLeft + localX;
    const contentY = viewport.scrollTop + localY;
    const step = event.deltaY < 0 ? 10 : -10;
    setTreeZoom((current) => {
      const next = clampTreeZoom(current + step);
      if (next === current) return current;
      const ratio = next / current;
      window.requestAnimationFrame(() => {
        viewport.scrollLeft = contentX * ratio - localX;
        viewport.scrollTop = contentY * ratio - localY;
      });
      return next;
    });
  }, []);

  useEffect(() => {
    const viewports = [treeViewportRef.current, expandedTreeViewportRef.current]
      .filter((viewport): viewport is HTMLDivElement => viewport !== null);
    for (const viewport of viewports) {
      viewport.addEventListener("wheel", onTreeWheel, { passive: false });
    }
    return () => {
      for (const viewport of viewports) viewport.removeEventListener("wheel", onTreeWheel);
    };
  }, [onTreeWheel, treeExpanded, treeImageUrl]);

  const onTreePointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (!event.isPrimary || event.button !== 0) return;
    finishTreeDrag();
    const viewport = event.currentTarget;
    treeDragRef.current = {
      pointerId: event.pointerId,
      viewport,
      startClientX: event.clientX,
      startClientY: event.clientY,
      startScrollLeft: viewport.scrollLeft,
      startScrollTop: viewport.scrollTop,
    };
    viewport.classList.add("is-dragging");
    viewport.setPointerCapture(event.pointerId);
    viewport.focus({ preventScroll: true });
    event.preventDefault();
  };

  const onTreePointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    const drag = treeDragRef.current;
    if (!drag || drag.pointerId !== event.pointerId) return;
    drag.viewport.scrollLeft = drag.startScrollLeft - (event.clientX - drag.startClientX);
    drag.viewport.scrollTop = drag.startScrollTop - (event.clientY - drag.startClientY);
    event.preventDefault();
  };

  const resetTreeView = (expanded: boolean) => {
    finishTreeDrag();
    setTreeZoom(100);
    const viewport = expanded ? expandedTreeViewportRef.current : treeViewportRef.current;
    window.requestAnimationFrame(() => {
      if (!viewport) return;
      viewport.scrollLeft = 0;
      viewport.scrollTop = 0;
    });
  };

  const treeControls = (showExpand: boolean, expanded: boolean) => (
    <div className="tree-controls" role="group" aria-label={t.treeViewerTitle}>
      <span className="tree-interaction-hint">{t.treeInteractionHint}</span>
      <span className="tree-zoom-level">{t.treeZoomLevel} <output>{treeZoom}%</output></span>
      <button type="button" title={t.treeResetZoom} onClick={() => resetTreeView(expanded)}>100%</button>
      {showExpand && (
        <button type="button" className="tree-expand-button" onClick={() => setTreeExpanded(true)}>
          {t.treeExpand}
        </button>
      )}
    </div>
  );

  return (
    <main>
      <header className="site-header">
        <div className="brand">
          <img src="/favicon.svg" alt="" width="44" height="44" />
          <div>
            <h1>{t.brandTitle}</h1>
            <p>{t.brandSubtitle}</p>
          </div>
          <span className="version-badge">V1.1</span>
        </div>
        <nav aria-label={t.navLabel}>
          <div className="language-toggle" role="group" aria-label="Language / 语言">
            <button type="button" className={locale === "en" ? "active" : ""} aria-pressed={locale === "en"} onClick={() => setLanguage("en")}>EN</button>
            <button type="button" className={locale === "zh" ? "active" : ""} aria-pressed={locale === "zh"} onClick={() => setLanguage("zh")}>中文</button>
          </div>
          <a href={methodsUrl} target="_blank" rel="noreferrer">{t.methods}</a>
          <a href={citationUrl} target="_blank" rel="noreferrer">{t.citation}</a>
          <a href={repositoryUrl} target="_blank" rel="noreferrer">GitHub</a>
        </nav>
      </header>

      <section className="workflow-strip" id="workflow" aria-label={t.workflowLabel}>
        <span className="eyebrow">{t.workflowEyebrow}</span>
        <strong>{t.workflowInput}</strong>
        <i aria-hidden="true">→</i>
        <strong>{t.workflowAlignment}</strong>
        <i aria-hidden="true">→</i>
        <strong>{t.workflowTree}</strong>
        <div className="workflow-actions">
          <button type="button" onClick={() => { setHistoryError(""); setHistoryOpen(true); }} disabled={busy}>
            {t.sessionHistory}
            {sessionHistory.length > 0 && <b>{sessionHistory.length}</b>}
          </button>
          <button
            type="button"
            onClick={clearCurrentResult}
            disabled={busy || (!job && !error && batchFailures.length === 0)}
          >
            {t.clearCurrentResult}
          </button>
        </div>
        <span className={`service-chip ${service}`}>
          {t.service[service]}
        </span>
      </section>

      <div className="workspace-grid">
        <section className="input-panel" aria-labelledby="input-title">
          <div className="mode-tabs" role="tablist" aria-label={t.inputTabs}>
            {(["single", "batch", "fasta"] as InputMode[]).map((item) => (
              <button
                key={item}
                type="button"
                role="tab"
                aria-selected={mode === item}
                className={mode === item ? "active" : ""}
                onClick={() => switchMode(item)}
              >
                {t.inputs[item].title}
              </button>
            ))}
          </div>

          <form onSubmit={run}>
            <div className="panel-heading">
              <span className="eyebrow">INPUT</span>
              <h2 id="input-title">{t.inputs[mode].title}</h2>
              <p>{t.inputs[mode].hint}</p>
            </div>

            {mode === "single" && (
              <label className="field-label">
                {t.sampleId}
                <input
                  value={sampleId}
                  onChange={(event) => setSampleId(event.target.value)}
                  placeholder={t.samplePlaceholder}
                  maxLength={60}
                  disabled={busy}
                />
              </label>
            )}

            <div
              className={`upload-zone${dragActive ? " is-dragging" : ""}`}
              onDragEnter={onDragEnter}
              onDragOver={onDragOver}
              onDragLeave={onDragLeave}
              onDrop={onDrop}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept={acceptedFiles[mode]}
                multiple={mode !== "fasta"}
                onChange={(event) => {
                  onFiles(event.target.files);
                  event.target.value = "";
                }}
                disabled={busy}
              />
              <input
                ref={folderInputRef}
                type="file"
                accept={acceptedFiles[mode]}
                multiple
                onChange={(event) => {
                  onFiles(event.target.files);
                  event.target.value = "";
                }}
                disabled={busy}
              />
              <span className="upload-mark" aria-hidden="true">＋</span>
              <strong>{dragActive ? t.dropActive : t.dropPrompt}</strong>
              <small>{selectedLabel}</small>
              <div className="upload-actions">
                <button type="button" onClick={() => fileInputRef.current?.click()} disabled={busy}>
                  {mode === "batch" ? t.chooseFiles : t.chooseFile}
                </button>
                <button type="button" onClick={() => folderInputRef.current?.click()} disabled={busy}>
                  {t.chooseFolder}
                </button>
              </div>
            </div>

            {mode === "batch" && batchGroups.length > 0 && (
              <div className="batch-preview" aria-label={t.batchGroups}>
                {batchGroups.slice(0, 6).map(([id, group]) => (
                  <span key={id}>{id}<b>{group.length}</b></span>
                ))}
                {batchGroups.length > 6 && <span>{t.additionalSamples(batchGroups.length - 6)}</span>}
                <button type="button" onClick={() => setSampleListOpen(true)}>
                  {t.viewAllSamples(batchGroups.length)}
                </button>
              </div>
            )}

            <button className="primary-button" type="submit" disabled={busy || files.length === 0 || service !== "ready"}>
              {busy ? t.running : t.start}
            </button>
            {busy && (
              <button className="stop-button" type="button" onClick={stop}>{t.stop}</button>
            )}
          </form>
        </section>

        <section className="result-panel" aria-labelledby="result-title">
          <div className="result-header">
            <div>
              <span className="eyebrow">RESULT</span>
              <h2 id="result-title">{t.result}</h2>
            </div>
            {job && <span className={`job-status ${job.status}`}>{prettyJobStatus(job.status, locale)}</span>}
          </div>

          <div aria-live="polite" aria-atomic="true">
            {error && <div className="error-box" role="alert">{error}</div>}
            {batchFailures.length > 0 && (
              <section className="batch-failures" aria-labelledby="batch-failures-title">
                <div>
                  <h3 id="batch-failures-title">{t.excludedSamples}</h3>
                  <p>{t.excludedSummary(batchFailures.length)}</p>
                </div>
                <div className="batch-failure-list">
                  {batchFailures.map((failure) => (
                    <div key={failure.sampleId}>
                      <strong>{failure.sampleId}</strong>
                      <span><b>{t.excludedReason}：</b>{failure.reason}</span>
                    </div>
                  ))}
                </div>
              </section>
            )}
            {!job && !error && (
              <div className="empty-state">
                <img src="/favicon.svg" alt="" width="54" height="54" />
                <h3>{t.waiting}</h3>
                <p>{t.waitingHint}</p>
              </div>
            )}
            {job && (job.status === "queued" || job.status === "running") && (
              <div className="progress-state">
                <div className="progress-copy">
                  <span>{batchStepText || progressMessage(job, locale, t.analyzing)}</span>
                  <strong>{Math.round(job.progress?.percent || 0)}%</strong>
                </div>
                <div className="progress-track" aria-label={t.progressLabel}>
                  <span style={{ width: `${Math.max(2, job.progress?.percent || 0)}%` }} />
                </div>
                <p>{t.keepOpen}</p>
              </div>
            )}
            {job?.status === "completed" && job.summary && (
              <div className="completed-state">
                {resultRows.length > 0 && (
                  <div className="typing-evidence">
                    <div className="typing-evidence-actions">
                      <span>{t.sequences(resultRows.length)}</span>
                      <button type="button" onClick={exportTypingResults}>{t.exportResults}</button>
                    </div>
                    <div className="table-wrap">
                      <table>
                        <thead><tr><th>{t.columns.sequence}</th><th>{t.columns.newGenotype}</th><th>{t.columns.oldGenotype}</th><th>{t.columns.newGroup}</th><th>{t.columns.oldGroup}</th><th>{t.columns.support}</th><th>{t.columns.status}</th></tr></thead>
                        <tbody>
                          {resultRows.map((row) => (
                            <tr key={row.sample_id}>
                              <td>{row.sample_id}</td>
                              <td>{row.predicted_new_genotype || "—"}</td>
                              <td>{row.predicted_old_genotype || "—"}</td>
                              <td>{row.predicted_new_group || "—"}</td>
                              <td>{row.predicted_old_group || "—"}</td>
                              <td>{percentLabel(row.support)}</td>
                              <td>{prettyStatus(row.status, locale)}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                    <p className="support-note">{t.supportNote}</p>
                  </div>
                )}

                {treeFilename && (
                  <figure className="tree-card">
                    {treeControls(true, false)}
                    <div
                      ref={treeViewportRef}
                      className="tree-viewport"
                      tabIndex={0}
                      aria-label={t.treeInteractionHint}
                      onPointerDown={onTreePointerDown}
                      onPointerMove={onTreePointerMove}
                      onPointerUp={(event) => finishTreeDrag(event.pointerId)}
                      onPointerCancel={(event) => finishTreeDrag(event.pointerId)}
                      onLostPointerCapture={(event) => finishTreeDrag(event.pointerId)}
                    >
                      <img
                        src={treeImageUrl}
                        alt={t.treeAlt}
                        draggable="false"
                        style={{ width: `${treeZoom}%` }}
                      />
                    </div>
                    <figcaption>{t.treeCaption}</figcaption>
                  </figure>
                )}

                <div className="download-row">
                  {Object.entries(job.files).map(([label, filename]) => (
                    <a key={label} href={resultFileUrl(job.job_id, filename)} download>{downloadLabel(label, locale)}</a>
                  ))}
                </div>
              </div>
            )}
          </div>
        </section>
      </div>

      {historyOpen && (
        <div className="modal-backdrop" role="presentation" onClick={() => setHistoryOpen(false)}>
          <section
            className="modal-card history-dialog"
            role="dialog"
            aria-modal="true"
            aria-labelledby="history-dialog-title"
            onClick={(event) => event.stopPropagation()}
          >
            <header className="modal-header">
              <div>
                <span className="eyebrow">HISTORY</span>
                <h2 id="history-dialog-title">{t.historyTitle}</h2>
                <p>{t.historyHint}</p>
              </div>
              <button type="button" className="modal-close" onClick={() => setHistoryOpen(false)}>{t.close}</button>
            </header>
            {historyError && <div className="modal-error" role="alert">{historyError}</div>}
            {sessionHistory.length === 0 ? (
              <div className="modal-empty">{t.historyEmpty}</div>
            ) : (
              <div className="history-list">
                {sessionHistory.map((entry) => (
                  <article key={entry.jobId}>
                    <div className="history-copy">
                      <strong>{entry.label}</strong>
                      <span>{t.inputs[entry.mode].title} · {submittedAtLabel(entry.submittedAt, locale)}</span>
                    </div>
                    <span className={`job-status ${entry.status}`}>{prettyJobStatus(entry.status, locale)}</span>
                    <button
                      type="button"
                      onClick={() => restoreHistoryResult(entry)}
                      disabled={historyLoadingId !== null}
                    >
                      {historyLoadingId === entry.jobId ? t.historyLoading : t.historyOpenResult}
                    </button>
                  </article>
                ))}
              </div>
            )}
          </section>
        </div>
      )}

      {sampleListOpen && (
        <div className="modal-backdrop" role="presentation" onClick={() => setSampleListOpen(false)}>
          <section
            className="modal-card sample-dialog"
            role="dialog"
            aria-modal="true"
            aria-labelledby="sample-dialog-title"
            onClick={(event) => event.stopPropagation()}
          >
            <header className="modal-header">
              <div>
                <span className="eyebrow">SAMPLES</span>
                <h2 id="sample-dialog-title">{t.sampleListTitle}</h2>
                <p>{t.sampleListHint(files.length, batchGroups.length)}</p>
              </div>
              <button type="button" className="modal-close" onClick={() => setSampleListOpen(false)}>{t.close}</button>
            </header>
            <div className="sample-list">
              {batchGroups.map(([id, group], index) => (
                <article key={id}>
                  <span className="sample-index">{String(index + 1).padStart(2, "0")}</span>
                  <div>
                    <strong>{id}</strong>
                    <span>{t.sampleFiles(group.length)}</span>
                  </div>
                  <ul>
                    {group.map((file) => <li key={`${file.name}-${file.size}`} title={file.name}>{file.name}</li>)}
                  </ul>
                </article>
              ))}
            </div>
          </section>
        </div>
      )}

      {treeExpanded && treeImageUrl && (
        <div className="modal-backdrop tree-backdrop" role="presentation" onClick={() => { finishTreeDrag(); setTreeExpanded(false); }}>
          <section
            className="modal-card tree-dialog"
            role="dialog"
            aria-modal="true"
            aria-labelledby="tree-dialog-title"
            onClick={(event) => event.stopPropagation()}
          >
            <header className="modal-header tree-dialog-header">
              <div>
                <span className="eyebrow">TREE</span>
                <h2 id="tree-dialog-title">{t.treeViewerTitle}</h2>
              </div>
              <button type="button" className="modal-close" onClick={() => { finishTreeDrag(); setTreeExpanded(false); }}>{t.close}</button>
            </header>
            {treeControls(false, true)}
            <div
              ref={expandedTreeViewportRef}
              className="tree-viewport is-expanded"
              tabIndex={0}
              aria-label={t.treeInteractionHint}
              onPointerDown={onTreePointerDown}
              onPointerMove={onTreePointerMove}
              onPointerUp={(event) => finishTreeDrag(event.pointerId)}
              onPointerCancel={(event) => finishTreeDrag(event.pointerId)}
              onLostPointerCapture={(event) => finishTreeDrag(event.pointerId)}
            >
              <img
                src={treeImageUrl}
                alt={t.treeAlt}
                draggable="false"
                style={{ width: `${treeZoom}%` }}
              />
            </div>
          </section>
        </div>
      )}

      <footer id="citation">
        <span>{t.researchOnly}</span>
        <span>V1.1 · 60ref · MAFFT 7.525 · IQ-TREE 3.0.1</span>
      </footer>
    </main>
  );
}
